name: Worflow for Debugging
on: workflow_dispatch
jobs:
  creating-artefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "This is a test file." > test.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: test.txt
  configuring-enviroment-variables:
    runs-on: ubuntu-latest
    needs: creating-artefacts
    steps:
      - name: Set 2 environment variables
        run: |
          echo ACTIONS_RUNNER_DEBUG=${{ vars.ACTIONS_RUNNER_DEBUG }} 
          echo ACTIONS_STEP_DEBUG=${{ vars.ACTIONS_STEP_DEBUG }}
  configuring-step-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Set step summary
        run: echo "This is a log about the step summary" >> $GITHUB_STEP_SUMMARY
      - name: Set other step summary
        run: echo "This is other log about the step summary" >> $GITHUB_STEP_SUMMARY
  adding-logs-by-step:
    runs-on: ubuntu-latest
    steps:
      - name: Add logs by step
        run: |
          echo "This is a log about the step"
          echo "This is another log about the step"
