name: My first workflow
run-name: Running my first workflow
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: [main]
jobs:
  testing-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
