name: Workflow CD
description: Testing a workflow CD
on: pull_request
permissions:
  contents: read
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: "Development"
    steps:
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: azure/docker-login@v2
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web app container
        uses: Azure/webapps-deploy@v2.2.17
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
          
