name: Worflow for PRs
run-name: Running my first workflow for PRs
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
jobs:
  testing-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo This is a PR workflow!!
