name: Workflow for PRs
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "*.md"
      - CODEOWNERS
      - package-lock.json
jobs:
  check-lines-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies for custom action
        run: npm install
        working-directory: ./.github/actions/total-changes
      - name: Get lines of code added and removed
        uses: ./.github/actions/total-changes
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
