name: Workflow for PRs
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "*.md"
      - CODEOWNERS
      - package-lock.json
jobs:
  check-lines-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PR total changes
        uses: christianncode/pr-total-changes@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
