name: Workflow for PRs
run-name: Running my first workflow for PRs
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
jobs:
  check-lines-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get lines of code added and removed
        id: diff
        uses: actions/github-script@v6
        with:
          script: |
            const diff = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.pull_request.base.sha,
              head: context.payload.pull_request.head.sha,
            });

            const additions = diff.data.ahead_by;
            const deletions = diff.data.behind_by;
            const totalChanges = additions + deletions;
            |-------------|---------------|---------------|
            | ${additions} | ${deletions} | ${totalChanges} |

            ${
              totalChanges > 500
                ? "❌ **Too many changes! The PR exceeds the limit of 500 lines.**"
                : "✅ **The PR is within the acceptable limit.**"
            }
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            });
