name: Workflow for PRs
run-name: Running my first workflow for PRs
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  check-lines-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get lines of code added and removed
        uses: ./.github/actions/total-changes
